// Code generated by entc, DO NOT EDIT.

package user

import (
	"github.com/andreylm/vm_test/pkg/ent/schema"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserName holds the string denoting the user_name vertex property in the database.
	FieldUserName = "user_name"
	// FieldFullName holds the string denoting the full_name vertex property in the database.
	FieldFullName = "full_name"
	// FieldCity holds the string denoting the city vertex property in the database.
	FieldCity = "city"
	// FieldBirthDate holds the string denoting the birth_date vertex property in the database.
	FieldBirthDate = "birth_date"
	// FieldDepartment holds the string denoting the department vertex property in the database.
	FieldDepartment = "department"
	// FieldGender holds the string denoting the gender vertex property in the database.
	FieldGender = "gender"
	// FieldExperienceYears holds the string denoting the experience_years vertex property in the database.
	FieldExperienceYears = "experience_years"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserName,
	FieldFullName,
	FieldCity,
	FieldBirthDate,
	FieldDepartment,
	FieldGender,
	FieldExperienceYears,
}

var (
	fields = schema.User{}.Fields()

	// descExperienceYears is the schema descriptor for experience_years field.
	descExperienceYears = fields[7].Descriptor()
	// ExperienceYearsValidator is a validator for the "experience_years" field. It is called by the builders before save.
	ExperienceYearsValidator = descExperienceYears.Validators[0].(func(int) error)
)
