// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/andreylm/vm_test/pkg/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserName holds the value of the "user_name" field.
	UserName string `json:"UserName"`
	// FullName holds the value of the "full_name" field.
	FullName string `json:"FullName"`
	// City holds the value of the "city" field.
	City string `json:"City"`
	// BirthDate holds the value of the "birth_date" field.
	BirthDate time.Time `json:"BirthDate"`
	// Department holds the value of the "department" field.
	Department string `json:"Department"`
	// Gender holds the value of the "gender" field.
	Gender string `json:"Gender"`
	// ExperienceYears holds the value of the "experience_years" field.
	ExperienceYears int `json:"ExperienceYears"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // user_name
		&sql.NullString{}, // full_name
		&sql.NullString{}, // city
		&sql.NullTime{},   // birth_date
		&sql.NullString{}, // department
		&sql.NullString{}, // gender
		&sql.NullInt64{},  // experience_years
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(values ...interface{}) error {
	if m, n := len(values), len(user.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	u.ID = int64(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field user_name", values[0])
	} else if value.Valid {
		u.UserName = value.String
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field full_name", values[1])
	} else if value.Valid {
		u.FullName = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field city", values[2])
	} else if value.Valid {
		u.City = value.String
	}
	if value, ok := values[3].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field birth_date", values[3])
	} else if value.Valid {
		u.BirthDate = value.Time
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field department", values[4])
	} else if value.Valid {
		u.Department = value.String
	}
	if value, ok := values[5].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field gender", values[5])
	} else if value.Valid {
		u.Gender = value.String
	}
	if value, ok := values[6].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field experience_years", values[6])
	} else if value.Valid {
		u.ExperienceYears = int(value.Int64)
	}
	return nil
}

// Update returns a builder for updating this User.
// Note that, you need to call User.Unwrap() before calling this method, if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return (&UserClient{u.config}).UpdateOne(u)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteString(", user_name=")
	builder.WriteString(u.UserName)
	builder.WriteString(", full_name=")
	builder.WriteString(u.FullName)
	builder.WriteString(", city=")
	builder.WriteString(u.City)
	builder.WriteString(", birth_date=")
	builder.WriteString(u.BirthDate.Format(time.ANSIC))
	builder.WriteString(", department=")
	builder.WriteString(u.Department)
	builder.WriteString(", gender=")
	builder.WriteString(u.Gender)
	builder.WriteString(", experience_years=")
	builder.WriteString(fmt.Sprintf("%v", u.ExperienceYears))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User

func (u Users) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
